# Generated by Django 4.0.3 on 2022-04-08 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название ПО', max_length=100, verbose_name='Название')),
                ('version', models.CharField(help_text='Введите версию', max_length=100, verbose_name='Версия')),
                ('free', models.BooleanField(default=True, help_text='Укажите бесплатное ли ПО', verbose_name='Бесплатное ПО')),
                ('soft_info', models.TextField(help_text='Заполните информацию о продукте', max_length=1000, verbose_name='О продукте')),
            ],
            options={
                'db_table': 'Software',
            },
        ),
        migrations.CreateModel(
            name='Installed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license', models.CharField(help_text='Укажите условия лицензии', max_length=100, verbose_name='Лицензия')),
                ('cert', models.BooleanField(default=False, help_text='Укажите нужен ли сертификат', verbose_name='Нужен сертификат')),
                ('cert_info', models.TextField(help_text='Укажите данные о сертификате ЭП', max_length=1000, verbose_name='Сертификат ЭП')),
                ('software', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.software')),
            ],
            options={
                'db_table': 'Installed',
            },
        ),
    ]
