# Generated by Django 4.0.3 on 2022-04-08 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_software_installed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Учетные записи', 'verbose_name_plural': 'Учетные записи'},
        ),
        migrations.AlterModelOptions(
            name='installed',
            options={'verbose_name': 'Установленное ПО', 'verbose_name_plural': 'Установленное ПО'},
        ),
        migrations.AlterModelOptions(
            name='software',
            options={'verbose_name': 'Программное обеспечение', 'verbose_name_plural': 'Программное обеспечение'},
        ),
        migrations.AlterModelOptions(
            name='workstation',
            options={'verbose_name': 'Рабочие станции', 'verbose_name_plural': 'Рабочие станции'},
        ),
        migrations.AlterField(
            model_name='installed',
            name='software',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='inventory.software'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='workstation',
            name='software',
        ),
        migrations.AddField(
            model_name='workstation',
            name='software',
            field=models.ManyToManyField(help_text='Добавьте программу', to='inventory.software', verbose_name='Программное обеспечение'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='user',
            field=models.ForeignKey(blank=True, default='', help_text='Добавьте пользователя', on_delete=django.db.models.deletion.PROTECT, to='inventory.account', verbose_name='Пользователь'),
            preserve_default=False,
        ),
    ]
