# Generated by Django 4.0.3 on 2022-04-11 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_installed_workstation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workstation',
            name='software',
        ),
        migrations.AddField(
            model_name='workstation',
            name='software',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.software'),
        ),
    ]
