# Generated by Django 4.0.3 on 2022-04-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_account_login_alter_workstation_hostname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workstation',
            name='cpu',
            field=models.CharField(blank=True, help_text='Введите модель процессора', max_length=100, null=True, verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='motherboard',
            field=models.CharField(blank=True, help_text='Введите модель платы', max_length=100, null=True, verbose_name='Материнская плата'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='ram',
            field=models.CharField(blank=True, help_text='Введите модель памяти', max_length=100, null=True, verbose_name='ОЗУ'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='storage',
            field=models.CharField(blank=True, help_text='Введите модель накопителя', max_length=100, null=True, verbose_name='Накопитель'),
        ),
    ]
