# Generated by Django 4.0.3 on 2022-04-13 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_certificate_installed_cetrificate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='installed',
            old_name='cetrificate',
            new_name='certificate',
        ),
    ]
